namespace MindMirror.Services;

public static class StringsPages
{
    public static readonly Dictionary<string, (string En, string Ar)> Map = new()
    {
        // Common
        ["common.search"] = ("Search", "بحث"),
        ["common.clear"] = ("Clear", "مسح"),
        ["common.filter"] = ("Filter", "تصفية"),
        ["common.callnow"] = ("Call now", "اتصل الآن"),
        ["common.website"] = ("Website", "الموقع الإلكتروني"),
        ["common.readmore"] = ("Read more", "اقرأ المزيد"),
        ["common.minread"] = ("min read", "دقيقة قراءة"),
        ["common.verified"] = ("Last verified:", "آخر تحقق:"),
        ["common.notverified"] = ("Not yet verified. Please confirm by phone before visiting.", "لم يتم التحقق بعد. يرجى التأكد هاتفياً قبل الزيارة."),
        ["common.free"] = ("Free", "مجاني"),
        ["common.24h"] = ("24 hours", "24 ساعة"),

        // Categories
        ["cat.Anxiety"] = ("Anxiety", "القلق"),
        ["cat.Depression"] = ("Depression", "الاكتئاب"),
        ["cat.Sleep"] = ("Sleep", "النوم"),
        ["cat.Stress"] = ("Stress", "التوتر"),
        ["cat.Self-care"] = ("Self-care", "العناية بالنفس"),
        ["cat.General"] = ("General", "عام"),

        // Resource types
        ["type.Hotline"] = ("Hotline", "خط ساخن"),
        ["type.Hospital"] = ("Hospital", "مستشفى"),
        ["type.Clinic"] = ("Clinic", "عيادة"),
        ["type.Support group"] = ("Support group", "مجموعة دعم"),
        ["type.Online service"] = ("Online service", "خدمة عبر الإنترنت"),
        ["type.NGO"] = ("NGO", "منظمة أهلية"),

        // Governorates
        ["gov.Cairo"] = ("Cairo", "القاهرة"),
        ["gov.Qalyubia"] = ("Qalyubia", "القليوبية"),
        ["gov.Sharqia"] = ("Sharqia", "الشرقية"),
        ["gov.Monufia"] = ("Monufia", "المنوفية"),
        ["gov.Dakahlia"] = ("Dakahlia", "الدقهلية"),
        ["gov.Gharbia"] = ("Gharbia", "الغربية"),
        ["gov.Alexandria"] = ("Alexandria", "الإسكندرية"),
        ["gov.Port Said"] = ("Port Said", "بورسعيد"),
        ["gov.Beni Suef"] = ("Beni Suef", "بني سويف"),
        ["gov.Minya"] = ("Minya", "المنيا"),
        ["gov.Assiut"] = ("Assiut", "أسيوط"),
        ["gov.Sohag"] = ("Sohag", "سوهاج"),
        ["gov.Aswan"] = ("Aswan", "أسوان"),

        // Help
        ["help.intro"] = ("Asking for help is a strong and brave step. You don't have to wait until things are \"bad enough\".",
                          "طلب المساعدة خطوة قوية وشجاعة. لا يلزمك أن تنتظر حتى تصبح الأمور «سيئة بما يكفي»."),
        ["help.urgent.title"] = ("In immediate danger?", "هل أنت في خطر فوري؟"),
        ["help.urgent.text1"] = ("If you might hurt yourself or someone else, call emergency services now:",
                                 "إذا كنت قد تؤذي نفسك أو شخصاً آخر، فاتصل بالطوارئ الآن:"),
        ["help.urgent.text2"] = (". If you can, tell someone near you.", ". وإن استطعت، أخبر شخصاً قريباً منك."),
        ["help.hotline.title"] = ("Mental health hotline", "الخط الساخن للصحة النفسية"),
        ["help.pro.title"] = ("See a professional", "راجع مختصاً"),
        ["help.pro.text"] = ("A psychiatrist or licensed psychologist can assess what you're going through and talk through treatment options.",
                             "يمكن للطبيب النفسي أو الأخصائي النفسي المرخّص تقييم ما تمرّ به ومناقشة خيارات العلاج."),
        ["help.trust.title"] = ("Talk to someone you trust", "تحدّث إلى شخص تثق به"),
        ["help.trust.text"] = ("A friend or family member can be a good first step. You can say: \"I haven't been feeling like myself lately and I'd like to talk.\"",
                               "قد يكون الصديق أو أحد أفراد العائلة بداية جيدة. يمكنك أن تقول: «لم أكن على طبيعتي مؤخراً وأحب أن أتحدث معك»."),
        ["help.hospitals.title"] = ("Hospitals & hotlines", "المستشفيات والخطوط الساخنة"),
        ["help.hospitals.text"] = ("Find mental health hospitals across Egypt and call them directly.",
                                   "اعثر على مستشفيات الصحة النفسية في أنحاء مصر واتصل بها مباشرة."),

        // Privacy
        ["privacy.intro"] = ("MindMirror is built to respect your privacy.", "تم بناء MindMirror ليحترم خصوصيتك."),
        ["privacy.1h"] = ("Self-Check answers", "إجابات الاختبار الذاتي"),
        ["privacy.1b"] = (" are calculated in your browser. They are never sent to our server or stored.",
                          " تُحسب داخل متصفحك. لا تُرسل إلى خادمنا ولا تُخزَّن أبداً."),
        ["privacy.2h"] = ("We don't ask for accounts", "لا نطلب إنشاء حسابات"),
        ["privacy.2b"] = (" or personal information from visitors.", " أو معلومات شخصية من الزوار."),
        ["privacy.3h"] = ("Cookies:", "ملفات تعريف الارتباط:"),
        ["privacy.3b"] = (" we use one cookie to keep administrators signed in and one to remember your language choice. Neither is used for tracking.",
                          " نستخدم ملفاً واحداً لإبقاء المشرفين مسجّلين الدخول وآخر لتذكّر لغتك. لا يُستخدم أي منهما للتتبّع."),
        ["privacy.4h"] = ("Saved in your browser:", "المحفوظ في متصفحك:"),
        ["privacy.4b"] = (" your theme choice (light/dark) and, if you use the Mood Journal or Safety Plan, your entries. These stay on your device and are never sent to us.",
                          " اختيارك للمظهر (فاتح/داكن)، وإن استخدمت مفكرة المزاج أو خطة الأمان فإدخالاتك أيضاً. تبقى على جهازك ولا تُرسل إلينا أبداً."),
        ["privacy.5h"] = ("Fonts:", "الخطوط:"),
        ["privacy.5b"] = (" this site loads fonts from Google Fonts, which means your browser contacts Google's servers.",
                          " يحمّل هذا الموقع الخطوط من Google Fonts، أي أن متصفحك يتصل بخوادم Google."),
        ["privacy.footer"] = ("The content here is educational and is not medical advice, diagnosis, or treatment.",
                              "المحتوى هنا تثقيفي وليس نصيحة طبية ولا تشخيصاً ولا علاجاً."),

        // Error
        ["error.404.title"] = ("Page not found", "الصفحة غير موجودة"),
        ["error.404.text"] = ("The page you're looking for doesn't exist or was moved.", "الصفحة التي تبحث عنها غير موجودة أو تم نقلها."),
        ["error.title"] = ("Something went wrong", "حدث خطأ ما"),
        ["error.text"] = ("Please try again in a moment.", "يرجى المحاولة مرة أخرى بعد قليل."),
        ["error.home"] = ("Back to home", "العودة إلى الرئيسية"),

        // Articles
        ["articles.search.ph"] = ("Search articles...", "ابحث في المقالات..."),
        ["articles.allcat"] = ("All categories", "كل التصنيفات"),
        ["articles.empty"] = ("No articles found. Try a different word or category.", "لا توجد مقالات. جرّب كلمة أو تصنيفاً مختلفاً."),
        ["pager.prev"] = ("Previous", "السابق"),
        ["pager.next"] = ("Next", "التالي"),
        ["pager.page"] = ("Page", "صفحة"),
        ["pager.of"] = ("of", "من"),
        ["art.back"] = ("Back to articles", "العودة إلى المقالات"),
        ["art.notice1"] = ("This article is for education only. If you're struggling, see", "هذا المقال للتوعية فقط. إذا كنت تواجه صعوبة، فتفضّل بزيارة صفحة"),
        ["art.related"] = ("Related articles", "مقالات ذات صلة"),

        // Resources
        ["res.title"] = ("Support Directory", "دليل الدعم"),
        ["res.lead"] = ("Hotlines, clinics, and services you can contact. Always check details before you go or call.",
                        "خطوط ساخنة وعيادات وخدمات يمكنك التواصل معها. تأكد دائماً من التفاصيل قبل الذهاب أو الاتصال."),
        ["res.alltypes"] = ("All types", "كل الأنواع"),
        ["res.allcities"] = ("All cities", "كل المدن"),
        ["res.empty1"] = ("Nothing listed yet for this filter. In an emergency, call emergency services or see",
                          "لا توجد نتائج لهذه التصفية. في حالة الطوارئ اتصل بالطوارئ أو انتقل إلى"),

        // Hospitals
        ["hosp.title"] = ("Hospitals & Hotlines", "المستشفيات والخطوط الساخنة"),
        ["hosp.lead"] = ("Tap \"Call now\" to call directly from your phone. On a computer, copy the number.",
                         "اضغط «اتصل الآن» للاتصال مباشرة من هاتفك. على الكمبيوتر، انسخ الرقم."),
        ["hosp.danger"] = ("In immediate danger? Call emergency services now:", "في خطر فوري؟ اتصل بالطوارئ الآن:"),
        ["hosp.hotlines"] = ("Hotlines", "الخطوط الساخنة"),
        ["hosp.hospitals"] = ("Mental health hospitals", "مستشفيات الصحة النفسية"),
        ["hosp.search.ph"] = ("Search by name or area...", "ابحث بالاسم أو المنطقة..."),
        ["hosp.allgov"] = ("All governorates", "كل المحافظات"),
        ["hosp.none"] = ("No hospitals match your search. Try another governorate, or use the hotlines above.",
                         "لا توجد مستشفيات مطابقة لبحثك. جرّب محافظة أخرى أو استخدم الخطوط الساخنة أعلاه."),
        ["hosp.found"] = ("hospital(s) found", "مستشفى"),
        ["hosp.nophone1"] = ("No phone number listed yet. Call the national hotline", "لا يوجد رقم هاتف مسجّل بعد. اتصل بالخط الساخن الوطني"),
        ["hosp.nophone2"] = ("to be connected.", "ليتم تحويلك."),
        ["hosp.notice1"] = ("Phone numbers can change. If a number doesn't work, call the national hotline",
                            "قد تتغير أرقام الهواتف. إذا لم يعمل رقم، فاتصل بالخط الساخن الوطني"),

        // Conditions
        ["cond.title"] = ("Mental Health Conditions", "الحالات النفسية"),
        ["cond.lead"] = ("Clear, kind explanations of common conditions: what they are, what they feel like, how they're treated, and when to seek help.",
                         "شروحات واضحة ولطيفة للحالات الشائعة: ما هي، وكيف تبدو، وكيف تُعالج، ومتى تطلب المساعدة."),
        ["cond.notice"] = ("This information is educational and is not a diagnosis. Only a qualified professional can assess what you are going through.",
                           "هذه المعلومات للتثقيف وليست تشخيصاً. وحده المختص المؤهل يستطيع تقييم ما تمرّ به."),
        ["cond.search.ph"] = ("Search conditions...", "ابحث في الحالات..."),
        ["cond.nomatch"] = ("No condition matches your search.", "لا توجد حالة مطابقة لبحثك."),
        ["cond.learn"] = ("Learn more", "اعرف المزيد"),
        ["cond.all"] = ("All conditions", "كل الحالات"),
        ["cond.what"] = ("What is it?", "ما هي؟"),
        ["cond.signs"] = ("Common signs", "العلامات الشائعة"),
        ["cond.causes"] = ("What can cause it?", "ما الذي قد يسببها؟"),
        ["cond.treatment"] = ("Treatment and support", "العلاج والدعم"),
        ["cond.selfhelp"] = ("What you can do", "ما الذي يمكنك فعله"),
        ["cond.support"] = ("If someone you know is affected", "إذا كان شخص تعرفه يعاني منها"),
        ["cond.seek"] = ("When to get help", "متى تطلب المساعدة"),
        ["cond.print"] = ("Print this page", "اطبع هذه الصفحة"),
        ["cond.footer"] = ("This page is for education only and is not a diagnosis or medical advice. Treatment decisions should be made with a qualified professional.",
                           "هذه الصفحة للتثقيف فقط وليست تشخيصاً ولا نصيحة طبية. يجب اتخاذ قرارات العلاج مع مختص مؤهل."),
        ["cond.urgent1"] = ("If you are in immediate danger, call emergency services now:", "إذا كنت في خطر فوري، فاتصل بالطوارئ الآن:"),
        ["cond.urgent2"] = ("You can also go to the nearest emergency department or tell someone near you.",
                            "يمكنك أيضاً الذهاب إلى أقرب قسم طوارئ أو إخبار شخص قريب منك."),
    };
}